# Singular Value Decomposition (SVD)

**Singular Value Decomposition (SVD)** adalah teknik faktorisasi matriks untuk menguraikan sebuah matriks menjadi tiga matriks lainnya, sehingga dapat mengungkapkan aspek penting dari struktur matriks aslinya. SVD digunakan dalam berbagai aplikasi, seperti:

- Pemrosesan sinyal (*signal processing*)
- Kompresi gambar (*image compression*)
- Reduksi dimensi pada *machine learning*
- Sistem rekomendasi
- Analisis data

Materi ini mengasumsikan bahwa pembaca memiliki pengetahuan dasar aljabar linear, khususnya mengenai:

- Norma vektor dan matriks
- Rank matriks
- Dekomposisi eigen (nilai eigen dan vektor eigen)
- Vektor ortonormal
- Proyeksi linear

---

# Definisi Matematis

Dekomposisi nilai singular (*Singular Value Decomposition*) dari suatu matriks riil $A$ berukuran $m \times n$ dinyatakan sebagai:

$$
A = U \Sigma V^T
$$

dengan:

## 1. Matriks U

$U$ adalah matriks ortogonal berukuran $m \times m$.

Sifatnya:

$$
U^T U = UU^T = I
$$

Kolom-kolom pada matriks $U$ disebut **vektor singular kiri** (*left singular vectors*) dari matriks $A$.

---

## 2. Matriks Σ (Sigma)

$\Sigma$ adalah matriks diagonal persegi panjang berukuran $m \times n$ yang berisi nilai singular pada diagonal utamanya.

Bentuk umum:

$$
\Sigma =
\begin{bmatrix}
\sigma_1 & 0 & \cdots & 0\\
0 & \sigma_2 & \cdots & 0\\
\vdots & \vdots & \ddots & \vdots\\
0 & 0 & \cdots & \sigma_r
\end{bmatrix}
$$

dengan:

$$
\sigma_1 \ge \sigma_2 \ge \cdots \ge \sigma_r \ge 0
$$

di mana:

- $\sigma_i$ disebut **nilai singular** (*singular values*)
- Semua nilai singular bernilai non-negatif
- Banyaknya nilai singular yang tidak nol sama dengan **rank** matriks $A$

---

## 3. Matriks $V^T$

$V^T$ adalah transpose dari matriks ortogonal $V$ berukuran $n \times n$.

Sifatnya:

$$
V^T V = VV^T = I
$$

Kolom-kolom matriks $V$ disebut **vektor singular kanan** (*right singular vectors*) dari matriks $A$.

---

# Interpretasi SVD

SVD memecah transformasi matriks $A$ menjadi tiga tahap:

1. **$V^T$** melakukan rotasi atau refleksi data.
2. **$\Sigma$** melakukan penskalaan (*scaling*) berdasarkan nilai singular.
3. **$U$** melakukan rotasi atau refleksi hasil transformasi sebelumnya.

Dengan demikian:

$$
A = U \Sigma V^T
$$

menunjukkan bahwa matriks asli dapat direkonstruksi kembali dari ketiga komponen tersebut.

---

# Kesimpulan

Singular Value Decomposition (SVD) adalah metode yang sangat penting dalam aljabar linear karena mampu menguraikan suatu matriks menjadi tiga komponen utama, yaitu:

$$
A = U \Sigma V^T
$$

di mana:

- $U$ berisi vektor singular kiri,
- $\Sigma$ berisi nilai singular,
- $V^T$ berisi vektor singular kanan.

Dekomposisi ini banyak digunakan dalam kompresi data, analisis citra, reduksi dimensi, dan berbagai algoritma machine learning.

In [10]:
import numpy as np

A = np.array([
    [1, 1, 0],
    [2, 1, 1],
    [1, 0, 3]
])

# Singular Value Decomposition
U, S, VT = np.linalg.svd(A)

print("Matrix U:")
print(U)

print("\nSingular Values:")
print(S)

print("\nMatrix V^T:")
print(VT)

# Ubah S menjadi matriks diagonal Sigma
Sigma = np.diag(S)

print("\nMatrix Sigma:")
print(Sigma)

# Rekonstruksi A
hasil = U @ Sigma @ VT

print("\nHasil U @ Sigma @ V^T:")
print(np.round(hasil, 10))

Matrix U:
[[-0.21132487 -0.57735027 -0.78867513]
 [-0.57735027 -0.57735027  0.57735027]
 [-0.78867513  0.57735027 -0.21132487]]

Singular Values:
[3.73205081 2.         0.26794919]

Matrix V^T:
[[-0.57735027 -0.21132487 -0.78867513]
 [-0.57735027 -0.57735027  0.57735027]
 [ 0.57735027 -0.78867513 -0.21132487]]

Matrix Sigma:
[[3.73205081 0.         0.        ]
 [0.         2.         0.        ]
 [0.         0.         0.26794919]]

Hasil U @ Sigma @ V^T:
[[ 1.  1.  0.]
 [ 2.  1.  1.]
 [ 1. -0.  3.]]
